In [2]:
import numpy as np

# Create a 1D NumPy array of numbers from 0 to 20 with step size 2.
arr = np.arange(0,10,2)
print(arr)

[0 2 4 6 8]


In [3]:
# Generate a 5×5 identity matrix.
from numpy import random
arr = random.randint(50,size=(5,5))
print(arr)

[[ 5 11 14 10 19]
 [15 36 41 40 27]
 [39 28 13 25 44]
 [11 20 16 48 14]
 [35 44 42  9 33]]


In [4]:
# Create a 3×3 array filled with random numbers between 0 and 1.
arr = random.rand(3,3)
print(arr)

[[0.75071143 0.50120632 0.21625274]
 [0.17361097 0.83634762 0.42029865]
 [0.4543811  0.21434332 0.76374064]]


In [5]:
# Reshape a 1D array of 12 numbers into a 3×4 matrix.
arr =np.array([1,2,3,4,5,6,7,8,9,10,11,12])
print(np.reshape(arr,(3,4)))

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [6]:
# Create a NumPy array of 10 elements where every element is 5.
arr = np.full(10,5)
print(arr)

[5 5 5 5 5 5 5 5 5 5]


In [7]:
# Given a 2D array, extract the second row.
arr = np.array([[1,2,3],[4,5,6]])
print(arr[1])

[4 5 6]


In [8]:
# Select all elements greater than 50 from a random 4×4 matrix.
arr = random.randint(100,size=(4,4))
print(arr)
filter_no = np.where (arr> 50)
print(filter_no)

[[81 77 12 64]
 [71 37 18 41]
 [41 76 61 21]
 [17 84 50 91]]
(array([0, 0, 0, 1, 2, 2, 3, 3]), array([0, 1, 3, 0, 1, 2, 1, 3]))


In [9]:
# Reverse a NumPy array without using loops.
arr = np.arange(10,0,-1)
print(arr)

[10  9  8  7  6  5  4  3  2  1]


In [10]:
# Replace all negative values in an array with 0.
arr = np.array([30,-10,9,-8,4,1,-9])
arr[arr < 0] = 0
print("Modified Array:", arr)

Modified Array: [30  0  9  0  4  1  0]


In [11]:
# Find the mean, median, variance, and standard deviation of a dataset [2, 4, 6, 8, 10].
arr = np.array([2, 4, 6, 8, 10])
print("Mean :",np.mean(arr))
print("median :",np.median(arr))
print("variance :",np.var(arr))
print("standard deviation :",np.std(arr))

Mean : 6.0
median : 6.0
variance : 8.0
standard deviation : 2.8284271247461903


In [ ]:
# Normalize an array [1, 2, 3, 4, 5] to the range [0, 1].
arr = np.array([1,2,3,4,5])
reshape_arr = np.reshape(arr,[0,1])
print(reshape_arr)

ValueError: cannot reshape array of size 5 into shape (0,1)